name: Build and Trigger Deployment
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2 # checkout repository
      - uses: actions/checkout@v4 # install bun
      - name: Create dist worktree
        run: git worktree add dist # "checks out" the dist branch in the dist/ directory
      - name: Build site with bun
        run: |
          bun install
          bun run build
      - name: Commit build artifacts to dist branch
        run: |
          cd dist
          git remote set-url origin "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git add .
          git commit -m "Updates" # TODO: expressive commit message
          git push origin dist
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: trigger laclark.me build
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: token ${{ secrets.BUILD_TRIGGER_TOKEN }}" \
             https://api.github.com/repos/lucdar/laclark.me/dispatches \
             -d '{"event_type": "trigger-deploy"}'
